apiVersion: v1
kind: Service
metadata:
  name: micro-two
  labels:
    app: micro-two
spec:
  selector:
    app: micro-two
  ports:
  - name: http
    port: 80
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: micro-two-nodeport
  labels:
    app: micro-two
spec:
  selector:
    app: micro-two
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    nodePort: 30002
    protocol: TCP
  type: NodePort 