apiVersion: v1
kind: Service
metadata:
  name: micro-one
  labels:
    app: micro-one
spec:
  selector:
    app: micro-one
  ports:
  - name: http
    port: 80
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: micro-one-nodeport
  labels:
    app: micro-one
spec:
  selector:
    app: micro-one
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP
  type: NodePort 